In [ ]:
import pandas as pd
import numpy as np
from statsmodels.stats.outliers_influence import variance_inflation_factor

cidades = pd.read_excel('BRCidadesRegiao.xlsx')

In [ ]:
cidades = cidades[['regiao_imediata', 'cidade', 'estado', 'longitude', 'latitude', 'altitude',
'area_territorial', 'populacao_estimada', 'densidade_demografica', 'pib_per_capita', 'receitas_realizadas',
'despesas_empenhadas', 'saldo_receitas_despesas', 'unidades', 'unidades_urbanas', 'unidades_rurais', 'area_plantada', 'producao_graos',
'IDHM_Renda', 'IDHM_Longevidade', 'IDHM_Educacao', 'GVA_agropecuaria', 'GVA_industria', 'GVA_Servicos', 'GVA_publico',
'GDP', 'GDP_populacao', 'GDP_per_capita', 'estabelecimentos', 'carros', 'motos'
]].copy()

cidades.info()

cidades.replace([np.inf, -np.inf], np.nan, inplace=True)
cidades.dropna(inplace=True)
cidades

In [ ]:
cidades['estado'].unique()

cidades_SC = cidades[cidades['estado'] == 'TO'].copy()
cidades_SC

In [4]:
vif_dt = cidades_SC[[
'area_territorial', 'populacao_estimada', 'densidade_demografica', 'pib_per_capita', 'receitas_realizadas',
'despesas_empenhadas', 'saldo_receitas_despesas', 'unidades', 'unidades_urbanas', 'unidades_rurais', 'area_plantada', 'producao_graos',
'IDHM_Renda', 'IDHM_Longevidade', 'IDHM_Educacao', 'GVA_agropecuaria', 'GVA_industria', 'GVA_Servicos', 'GVA_publico',
'GDP', 'GDP_populacao', 'GDP_per_capita', 'estabelecimentos', 'carros', 'motos'
]]
vif_dt

,area_territorial,populacao_estimada,densidade_demografica,pib_per_capita,receitas_realizadas,despesas_empenhadas,saldo_receitas_despesas,unidades,unidades_urbanas,unidades_rurais,...,GVA_agropecuaria,GVA_industria,GVA_Servicos,GVA_publico,GDP,GDP_populacao,GDP_per_capita,estabelecimentos,carros,motos
1762,1895.691,2594,1.26,21850.43,11874.80853,11387.19982,487.60871,760.0,445.0,315.0,...,20312.55,2108.24,6802.38,16520.91,47378.25,2555,18543.35,27,190.0,318.0
1763,236.792,6892,21.93,18719.04,19456.10654,18280.86823,1175.23831,1323.0,1067.0,256.0,...,38385.50,7299.64,38614.35,36937.29,134621.18,6307,21344.72,42,472.0,1156.0
1764,1572.097,5346,3.59,20773.07,14911.35440,14065.56031,845.79409,1726.0,1435.0,291.0,...,36098.32,3363.23,18963.87,32037.96,94300.34,5565,16945.25,78,623.0,897.0
1765,4019.251,6979,1.89,20625.98,16408.99741,15067.30943,1341.68798,2090.0,1607.0,483.0,...,60995.70,4076.10,15287.14,41025.41,125459.14,7340,17092.53,73,469.0,866.0
1766,1212.167,8396,6.91,38266.00,30056.82858,20520.71146,9536.11712,2605.0,2398.0,207.0,...,47184.39,49052.42,89.81,45665.68,270979.04,8526,31782.67,267,1410.0,1652.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1894,1083.600,22845,21.00,12708.47,48244.19187,43298.11245,4946.07942,5998.0,5193.0,805.0,...,12845.65,16504.13,97447.57,123291.51,270914.35,23130,11712.68,252,3500.0,12353.0
1895,707.185,1922,2.21,24990.62,11134.70662,10101.15689,1033.54973,478.0,284.0,194.0,...,24653.85,1429.88,5.71,12897.20,46014.97,1813,25380.57,13,145.0,225.0
1896,895.308,2729,2.34,11060.03,11606.73352,10138.20775,1468.52577,646.0,332.0,314.0,...,5193.45,885.60,3654.27,17289.17,28032.34,2518,11132.78,13,98.0,207.0
1897,1363.407,11734,8.00,13507.58,23870.26098,22429.72419,1440.53679,2916.0,1595.0,1321.0,...,12997.54,32475.08,32312.77,61920.24,153154.92,11622,13178.02,98,589.0,1003.0
1898,1186.430,11520,9.68,29024.18,30968.22241,27994.41695,2973.80546,3192.0,2705.0,487.0,...,22856.97,126.36,50427.93,66509.05,296574.04,11695,25359.05,110,848.0,3148.0

In [5]:
vif_data = pd.DataFrame()
vif_data['variavel'] = vif_dt.columns
vif_data['VIF'] = [variance_inflation_factor(vif_dt.values, i)
    for i in range(len(vif_dt.columns))]
round(vif_data,4)

vif_dt = cidades_SC[[
'area_territorial', 'populacao_estimada', 'pib_per_capita',
'saldo_receitas_despesas', 'IDHM_Educacao', 'GDP']]
vif_dt

C:\Users\rafae\AppData\Roaming\Python\Python311\site-packages\statsmodels\stats\outliers_influence.py:195: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

,area_territorial,populacao_estimada,pib_per_capita,saldo_receitas_despesas,IDHM_Educacao,GDP
1762,1895.691,2594,21850.43,487.60871,0.502,47378.25
1763,236.792,6892,18719.04,1175.23831,0.571,134621.18
1764,1572.097,5346,20773.07,845.79409,0.596,94300.34
1765,4019.251,6979,20625.98,1341.68798,0.524,125459.14
1766,1212.167,8396,38266.00,9536.11712,0.623,270979.04
...,...,...,...,...,...,...
1894,1083.600,22845,12708.47,4946.07942,0.623,270914.35
1895,707.185,1922,24990.62,1033.54973,0.593,46014.97
1896,895.308,2729,11060.03,1468.52577,0.425,28032.34
1897,1363.407,11734,13507.58,1440.53679,0.561,153154.92
1898,1186.430,11520,29024.18,2973.80546,0.570,296574.04

In [6]:
vif_data = pd.DataFrame()
vif_data['variavel'] = vif_dt.columns
vif_data['VIF'] = [variance_inflation_factor(vif_dt.values, i)
    for i in range(len(vif_dt.columns))]
vif_data

                  variavel        VIF
0         area_territorial   2.068732
1       populacao_estimada  56.795126
2           pib_per_capita   6.224092
3  saldo_receitas_despesas  43.986209
4            IDHM_Educacao   5.537539
5                      GDP   4.118682

In [7]:
vif_dt = vif_dt.copy()
for coluna in vif_dt.columns:
    print(coluna)
    out_max = vif_dt[coluna].quantile(0.75) + ((vif_dt[coluna].quantile(0.75) - vif_dt[coluna].quantile(0.25)) * 1.5)
    print(out_max)
    vif_dt[coluna] = vif_dt[coluna].apply(lambda x : out_max if x > out_max else x)
    out_min = vif_dt[coluna].quantile(0.25) - ((vif_dt[coluna].quantile(0.75) - vif_dt[coluna].quantile(0.25)) * 1.5)
    print(out_min)
    vif_dt[coluna] = vif_dt[coluna].apply(lambda x : out_min if x < out_min else x)
vif_dt

area_territorial
4504.28225
-1538.2557500000003
populacao_estimada
16436.25
-4481.75
pib_per_capita
34876.752499999995
-3404.4474999999966
saldo_receitas_despesas
4896.979832500003
-1323.0622075000026
IDHM_Educacao
0.7208750000000002
0.3678749999999999
GDP
243007.79499999998
-95252.72499999998

,area_territorial,populacao_estimada,pib_per_capita,saldo_receitas_despesas,IDHM_Educacao,GDP
1762,1895.691,2594.00,21850.4300,487.608710,0.502,47378.250
1763,236.792,6892.00,18719.0400,1175.238310,0.571,134621.180
1764,1572.097,5346.00,20773.0700,845.794090,0.596,94300.340
1765,4019.251,6979.00,20625.9800,1341.687980,0.524,125459.140
1766,1212.167,8396.00,34876.7525,4896.979833,0.623,243007.795
...,...,...,...,...,...,...
1894,1083.600,16436.25,12708.4700,4896.979833,0.623,243007.795
1895,707.185,1922.00,24990.6200,1033.549730,0.593,46014.970
1896,895.308,2729.00,11060.0300,1468.525770,0.425,28032.340
1897,1363.407,11734.00,13507.5800,1440.536790,0.561,153154.920
1898,1186.430,11520.00,29024.1800,2973.805460,0.570,243007.795

In [ ]:
colunas = ['area_territorial', 'populacao_estimada', 'pib_per_capita', 'saldo_receitas_despesas', 'IDHM_Educacao', 'GDP']
sel = colunas
cidadesz = vif_dt[sel].copy()
listaz = []
for coluna in colunas:
    if coluna != "cidade":
        print(coluna)
        listaz.insert(0, 'z_'+coluna)
        media = cidadesz[coluna].mean()
        dp = cidadesz[coluna].std()
        cidadesz['z_'+coluna] = cidadesz[coluna].apply(lambda x : (x - media) / dp)
cidadesz['totalz'] = cidadesz[listaz].sum(axis=1)
cidadesz['ranking'] = cidadesz['totalz'].rank(ascending=False)
cidadesz

In [ ]:
cidades_SC = cidades_SC.merge(cidadesz, right_index=True, left_index=True, how = 'left')
cidades_SC

In [ ]:
cidades_SC.sort_values(by='ranking')[0:10]
cidades_SC

In [ ]:
cidades_SC.sort_values(by='ranking', ascending=False)[0:10]
cidades_SC

In [ ]:
regioes = cidades.groupby(['estado','regiao_imediata'])[
    [
        'area_territorial', 'populacao_estimada',
        'pib_per_capita'  , 'saldo_receitas_despesas',
        'IDHM_Educacao'   , 'GDP'
    ]
].mean().reset_index().copy()

regioes_SC = regioes[regioes['estado'] == 'SC']

colunas = ['area_territorial', 'populacao_estimada', 'pib_per_capita', 'saldo_receitas_despesas', 'IDHM_Educacao', 'GDP']
sel = colunas
regioesz = regioes_SC[sel].copy()
listaz = []
for coluna in colunas:
    if (coluna != "estado") & (coluna != "regiao_imediata"):
        print(coluna)
        listaz.insert(0, 'z_'+coluna)
        media = regioesz[coluna].mean()
        dp = regioesz[coluna].std()
        regioesz['z_'+coluna] = regioesz[coluna].apply(lambda x : (x - media) / dp)
regioesz['totalz'] = regioesz[listaz].sum(axis=1)
regioesz['ranking'] = regioesz['totalz'].rank(ascending=False)
regioesz

In [ ]:
regioes_SC = regioes_SC.merge(regioesz, right_index=True, left_index=True, how = 'left')
regioes_SC

In [ ]:
regioes_SC.sort_values(by='ranking')[0:4]
regioes_SC

In [ ]:
regioes_SC.sort_values(by='ranking', ascending=False)[0:4]
regioes_SC